{% set name = "google-cloud-pubsublite" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-pubsublite-{{ version }}.tar.gz
  sha256: c652878f8ced3f50ce79cc42a25ef1293aadeb47101fce76da362751a6b76b67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - google-api-core >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - google-cloud-pubsub >=2.10.0,<3.0.0dev
    - grpcio >=1.38.1,<2.0.0dev
    - grpcio-status >=1.38.1,<2.0.0dev
    - overrides >=6.0.1,<7.0.0
    - python >=3.7

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-pubsublite
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Pub/Sub Lite API is designed to provide reliable, many-to-many, asynchronous messaging between applications.

extra:
  recipe-maintainers:
    - xylar
